ДЗ №1
VK-BMSTU-QA/homework-1-autumn-2024 pull request #5
Opened 2024-09-27 08:39 UTC by b0pof

2024-09-30 20:25 UTC, BeeHeather requested changes
Привет! Основные моменты:

 • Нужно однозначно декомпозировать проверки - можете их пронумеровать, или сделать ненумерованный список. Помните, что одна проверка - один автотест
 • В дополнение к предыдущему пункту - некоторые проверки у вас описаны в одном общем пункте, их нужно разделить; другие наоборот - слишком сильно декомпозированы
 • Предлагаю вам вместо раздела "Пароль и безопасность" взять "Просмотрщик" (он открывается из любого раздела Облака с мультимедиа). Его проще будет покрыть автотестами, и в целом это важный функционал

2024-09-30 20:25 UTC, BeeHeather commented on FullFocus.md
> +* При вводе названия города, приложение подсказывает названия выпадающим списком, ориентируясь на введенные буквы. Однако можно проигнорировать подсказки и ввести название несуществующего города, о ч
Две проверки в одной

2024-09-30 20:25 UTC, BeeHeather commented on FullFocus.md
> +* Там же в правом верхнем углу рядом с аватаркой есть кнопка **ваши заметки**. При нажатии появляется модальное окно, с помощью которого можно сделать быстрое действие в одном из сторонних сервисовЖ
Вот это можно не тестировать, это не относится к Облаку

2024-09-30 20:25 UTC, BeeHeather commented on FullFocus.md
> +* Результаты поиска:
Распишите две проверки аналогично вашим скринам

2024-09-30 20:25 UTC, BeeHeather commented on FullFocus.md
> +![new_folder_create_empty](img/new_folder_create_empty.png)
Распишите проверку на пустое название отдельно

2024-10-10 08:44 UTC, Olegsandrik commented on FullFocus.md
> +* Отображение кнопок авторизации через сторонние сервисы такие как **"Одноклассники", "Вконтаке", "Госулсуги"**
Сделали

2024-10-10 08:44 UTC, Olegsandrik commented on FullFocus.md
> +* Авторизация возможна **по QR-коду**.
Сделали

2024-10-10 08:45 UTC, Olegsandrik commented on FullFocus.md
> +## Авторизация
Сделали

2024-10-10 08:45 UTC, Olegsandrik commented on FullFocus.md
> +* Можно **получить ссылку на материал**.
Перефразировали

2024-10-10 09:15 UTC, BeeHeather approved these changes
Аппрув

2024-10-10 10:56 UTC, Olegsandrik approved these changes
Аппрув!

2024-10-10 10:58 UTC, mvp-mogila commented
Аппрув

2024-10-10 11:01 UTC, b0pof commented
Аппрув

2025-02-02 22:41 UTC, closed without merging